#!/bin/sh

cat > configure <<EOF
#!/bin/sh
set -e
qbs setup-toolchains --settings-dir .qbs-settings --type gcc /usr/bin/g++ gcc
qbs setup-qt --settings-dir .qbs-settings /usr/bin/qmake qt5
qbs config --settings-dir .qbs-settings profiles.qt5.baseProfile gcc
qbs config --settings-dir .qbs-settings --list
EOF
chmod 755 configure

cat > Makefile <<EOF
all:
	qbs build --settings-dir .qbs-settings -d build --command-echo-mode command-line --no-install profile:qt5 qbs.installRoot:/ qbs.installPrefix:usr $*

install:
	qbs install --settings-dir .qbs-settings -d build --no-build profile:qt5 qbs.installRoot:/ qbs.installPrefix:usr $*
EOF
