#!/bin/bash

set -e

msg() {
    lightblue='\033[1;34m'
    reset='\e[0m'
    echo -e "${lightblue}$@${reset}"
}

gpg_key="7D98B067FFEFDAA5F8941D4CDFA98DBF970012EE"

msg "== Export"
./flatpak-build export --gpg-key=$gpg_key

msg "== Synchronize $t"
./flatpak-build sync --dest=liri@liri.io:/srv/www/repo.liri.io/flatpak
